language: php

php:
  - 5.4

before_script:
  - mysql -e 'create database ilch2_test;'
  - pear config-set auto_discover 1
  - pear install phpunit/DbUnit
  - phpenv rehash
  - cd tests

script: phpunit .

notifications:
  webhooks:
    urls:
      - http://www.ilch.de/ilch2/versions/
    on_success: always
    on_failure: never
    on_start: false
