language: php

php:
  - 5.4
  - 5.5
  - 5.6

install:
  - development\bin\setup.sh travis
  - mysql -e 'create database ilch2_test;'


script: cd tests && ../development/bin/phpunit

notifications:
  webhooks:
    urls:
      - http://www.ilch.de/ilch2/versions/
    on_success: always
    on_failure: never
    on_start: false
